### PR TITLE
Add flag to disable network tests.

### PR DESCRIPTION
**Pull request by ezzieyguywuf**
The without this, it is impossible to run tests in a sandbox environment such as that used by gentoo's portage package manager.

Signed-off-by: Wolfgang E. Sanyer <WolfgangESanyer@gmail.com>

Thanks for the pull request!

By raising this pull request you confirm you are licensing your contribution under all licenses that apply to this project (see LICENSE) and that you have no patents covering your contribution.

If you care, my PR preferences are at https://github.com/ndmitchell/neil#contributions, but they're all guidelines, and I'm not too fussy - you don't have to read them.

### CODE REVIEW

**Comment by ndmitchell** [comment]
Thanks! Is a release useful to get this into the packaging stuff?

**Comment by ezzieyguywuf** [comment]
Yes a release is most definitely helpful, as we only repackage for new
releases.

Thank you for your help!

**Comment by ndmitchell** [comment]
Done - 5.0.18.1 now out.

**Comment by ezzieyguywuf** [comment]
Thank you!

**Pull request merged**
