### PR TITLE
Add an upper bound on http-conduit.

### LINKED ISSUE #234: Compilation error when installing using cabal
## Error

```
% cabal install hoogle
Resolving dependencies...
Configuring hoogle-5.0.16...
Building hoogle-5.0.16...
Failed to install hoogle-5.0.16
Build log ( /Users/raxod502/.cabal/logs/ghc-8.2.2/hoogle-5.0.16-1WHC7CX0BdqGIiRCx4UaUb.log ):
cabal: Entering directory '/var/folders/z2/2q4hmwtn0kl4_9rkqqzg8zs00000gn/T/cabal-tmp-56972/hoogle-5.0.16'
Configuring hoogle-5.0.16...
Preprocessing library for hoogle-5.0.16..
Building library for hoogle-5.0.16..
[ 1 of 28] Compiling General.IString  ( src/General/IString.hs, dist/build/General/IString.o )
[ 2 of 28] Compiling General.Str      ( src/General/Str.hs, dist/build/General/Str.o )
[ 3 of 28] Compiling General.Conduit  ( src/General/Conduit.hs, dist/build/General/Conduit.o )
[ 4 of 28] Compiling General.Template ( src/General/Template.hs, dist/build/General/Template.o )
[ 5 of 28] Compiling General.Util     ( src/General/Util.hs, dist/build/General/Util.o )
[ 6 of 28] Compiling General.Timing   ( src/General/Timing.hs, dist/build/General/Timing.o )
[ 7 of 28] Compiling General.Log      ( src/General/Log.hs, dist/build/General/Log.o )
[ 8 of 28] Compiling Input.Download   ( src/Input/Download.hs, dist/build/Input/Download.o )

src/Input/Download.hs:38:9: error:
    • Couldn't match expected type ‘C.ResumableSource
                                      (ResourceT IO) Data.ByteString.Internal.ByteString’
                  with actual type ‘C.ConduitM
                                      i0 Data.ByteString.Internal.ByteString (ResourceT IO) ()’
    • In the first argument of ‘(C.$$+-)’, namely
        ‘C.responseBody response’
      In a stmt of a 'do' block:
        C.responseBody response C.$$+- sinkFile file
      In the second argument of ‘($)’, namely
        ‘do response <- C.http request manager
            C.responseBody response C.$$+- sinkFile file’
    • Relevant bindings include
        response :: C.Response
                      (C.ConduitM
                         i0 Data.ByteString.Internal.ByteString (ResourceT IO) ())
          (bound at src/Input/Download.hs:37:9)
   |
38 |         C.responseBody response C.$$+- sinkFile file
   |         ^^^^^^^^^^^^^^^^^^^^^^^
cabal: Leaving directory '/var/folders/z2/2q4hmwtn0kl4_9rkqqzg8zs00000gn/T/cabal-tmp-56972/hoogle-5.0.16'
cabal: Error: some packages failed to install:
hoogle-5.0.16-1WHC7CX0BdqGIiRCx4UaUb failed during the building phase. The
exception was:
ExitFailure 1
```

## Installed packages

`cabal list --installed` gives [this](https://gist.github.com/raxod502/fec031bdfc52173b0a974c3e95d9888f).

## Versions

```
% ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.2.2
% cabal --version
cabal-install version 2.0.0.1
compiled using version 2.0.1.0 of the Cabal library
% stack --version
Version 1.6.3 x86_64 hpack-0.20.0
```

## Operating system

```
                    'c.          raxod502
                 ,xNMM.          ----------------
               .OMMMMo           OS: OS X El Capitan 10.11.6 15G18013 x86_64
               OMMM0,            Model: MacBookPro11,3
     .;loddo:' loolloddol;.      Kernel: 15.6.0
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 12 hours, 44 minutes
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 514
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: zsh 5.4.2
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 3008x1692@2x, 1440x900@2x
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: Kwm
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    Terminal: iTerm2
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   CPU: Intel i7-4980HQ (8) @ 2.80GHz
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.   GPU: Intel Iris Pro, NVIDIA GeForce GT 750M
    kMMMMMMMMMMMMMMMMMMMMMMd     Memory: 1749MiB / 16384MiB
     ;KMMMMMMMWXXWMMMMMMMk.
       .cooc,.    .,coo:.
```

### PR DESCRIPTION
**Pull request by 23Skidoo**
Fixes #234. Would be nice if you could also make a Hackage revision.

### CODE REVIEW

**Comment by hvr** [comment]
> Would be nice if you could also make a Hackage revision.

Make that about 50 revisions...

See https://matrix.hackage.haskell.org/package/hoogle

untitled

**Comment by 23Skidoo** [comment]
Right, though when people do `cabal install hoogle`, they usually want the latest one.

**Comment by hvr** [comment]
@23Skidoo ...and `cabal install hoogle` (or `build-depends: hoogle >= 5.0 && < 5.1` for that matter) doesn't guarantee they will get that one if the solver has enough pressure to fallback to a previous one. That's why Trustees can't just fixup the latest version of something but have to fix everything that's accessible to the cabal solver ;-)

**Comment by ndmitchell** [comment]
Thanks @23Skidoo and @hvr. I've added revisions for hoogle-5.0..5.16, but as @hvr points out, the failures with older Hoogle are a different issue (don't know what, if someone tells me and it impacts them, I'll happily revise another 25 odd versions).

I probably won't ever release this code, but will use it as a stepping stone to then upgrade to the latest http-conduit.

**Comment by hvr** [comment]
@ndmitchell just give matrix.hho a couple of minutes to catch up, and you'll see the compile failures there... :-)

**Comment by ndmitchell** [comment]
@hvr - I see it now, bound added to test one of them then will replicate. Although some of my packages fail with a "Fail (1 dep)" and clicking on it I can't see which dep it was. Any way to track that down? If not, might be a nice enhancement.

**Comment by hvr** [comment]
> Although some of my packages fail with a "Fail (1 dep)" and clicking on it I can't see which dep it was. Any way to track that down?

If you're referring to the GHC 7.8 column being dark red: That's due to https://github.com/vincenthz/hs-memory/issues/44 (see also https://github.com/haskell-infra/hackage-trustees/issues/119 for the larger issue)

> If not, might be a nice enhancement.

Indeed! This was actually a regression from the big rewrite of the backend for matrix v2 into matrix v3; but that's been handled by last year's GSOC project which brought the webui frontend from v2 to v3 as well... but there's still some loose ends to fixup before it can go live. TLDR: this is going to be addressed in the next major update...

**Comment by hvr** [comment]
The failures for recent hoogles of the kind

```
src/General/Conduit.hs:72:35:
    Not in scope: `BS.unsnoc'
    Perhaps you meant `BS.snoc' (imported from Data.ByteString.Char8)
<<ghc: 845086184 bytes, 1541 GCs, 13501702/51114944 avg/max bytes residency (8 samples), 105M in use, 0.00 INIT (0.00 elapsed), 0.48 MUT (0.53 elapsed), 0.49 GC (0.49 elapsed) :ghc>>
cabal: Failed to build hoogle-5.0.14 (which is required by exe:hoogle from hoogle-5.0.14).
```

are due to a too lax lower bound on `bytestring`; `unsnoc` was added in `bytestring-0.10.2`

**Comment by ndmitchell** [comment]
I've now removed the upper bounds on http-conduit and fixed the code to work, and also added lower bounds for bytestring and time, and released. With that, all 5.0 series packages have a clean matrix. Thanks for the alert and all the help!

**Pull request merged**
