### PR TITLE
[add] rough json support

### PR DESCRIPTION
**Pull request by lennart**
not sure if this is what you intended but I started to work on JSON support for hoogle 5 server.

this is by no means complete but I guess it's better to share it with you now to avoid duplicate work.

this uses the aeson parser/encoder and just implements the `ToJSON` typeclass for `Target`

### CODE REVIEW

**Comment by ndmitchell** [comment]
Thanks! I'll review tomorrow. A quick skim makes me think I'll just merge as is.

**Comment by lennart** [comment]
one that is opinionated and should be rviewed is that this will allow cross origin request from all websites. a thing that is currently only allowed for form embedding in hoogle4. please be aware of the implications.

it might be better to hide this behind a flag an allow customization of the hosts allowed 
…

**Comment by ndmitchell** [comment]
Looks good, certainly good enough to merge and deploy (that should happen in about 3 hours automatically).

I can't see any reason not to allow cross origin for the JSON. The main reason cross origin exists is to stop people hijacking local session state, but that's not an issue for Hoogle, so I think we'll be fine. Or can you think of another reason to disable the cross origin?

**Comment by ndmitchell** [comment]
Two issues from trying it out. 1, it should return [] for the empty query. 2, it should be limited to N results, eg 100, or we are going to send too much data and upset the server.

**Comment by ndmitchell** [comment]
I made those two tweaks as 4c25d0e4cab98975ae682573e110b34222cfdf60. @lennart - anything else required?

**Comment by lennart** [comment]
good. yes limiting is smart and also your code simplifies this some more.

…

**Pull request merged**
