### PR TITLE
Update to GHC 7.10 and Cabal 1.22.

### PR DESCRIPTION
**Pull request by bitonic**
The only controversial change in in `Cabal.hs`, see comment.

### CODE REVIEW

**Comment by bitonic** [comment]
Actually, I just realised that things fail currently on my machine---I'll check better tomorrow.

**Comment by ndmitchell** [comment]
It all looks awesome to me, thanks for the patch. I'd very much appreciate a fresh pull request :)

**Comment by ndmitchell** [comment]
These changes aren't perfect, there are a few issues after that, but they are definitely a very useful starting point, so I've merged them in anyway and will fix up from there. Thanks for your help!

**Comment by bitonic** [comment]
Thanks for merging!  `hoogle-index` wasn't working yesterday night and I didn't want to risk it.

**Comment by ndmitchell** [comment]
I've just released 4.2.37 which works with GHC 7.10

**Pull request merged**
