### PR TITLE
Add support for results as JSON while searching through commandline

### LINKED ISSUE #287: JSON output from command line
For many applications (e.g.: editor integration) it would be quite useful if we could have a machine-readable JSON output from the `hoogle` command line. It shouldn't be too hard, and it would prevent people from writing ad-hoc parsing code for the output of `hoogle`. It would also be nice if the output from `hoogle search -i --link` (i.e.: the package name and URL) could be included in this JSON output. I'm thinking something like this:

```
$ hoogle search --json Just
[
    {
        "package": "Cabal",
        "module": "Distribution.Compat.Prelude.Internal",
        "identifier": "Just",
        "type": "a -> Maybe a",
        "url": "file:///nix/store/izd6sl5dvgxijzdxcg1zw77q61k7jn3l-ghc-8.4.3-doc/share/doc/ghc/html/libraries/Cabal-2.2.0.1/Distribution-Compat-Prelude-Internal.html#v:Just"
    },
    {
        "package": "accelerate",
        "module": "Data.Array.Accelerate.Data.Maybe",
        "identifier": "Just",
        "type": "a -> Maybe a",
        "url": "file:///nix/store/gzj1q15695brh95dsjdxpj8s33rc17sq-accelerate-1.2.0.0-doc/share/doc/html/Data-Array-Accelerate-Data-Maybe.html#v:Just"
    },
    ...
]
```

### PR DESCRIPTION
**Pull request by iAmMrinal0**
Fixes #287 

Add `--json` flag to get results as JSON

### CODE REVIEW

**Comment by ndmitchell** [comment]
Thanks! Would you like me to make a release including this patch?

**Comment by iAmMrinal0** [comment]
Sure. That would be helpful.

**Comment by ndmitchell** [comment]
It might have to wait until Monday (I may well be away from the computer til then), but will do it when I can.

**Comment by iAmMrinal0** [comment]
Cool, no issues. Thanks!

**Comment by ndmitchell** [comment]
I managed to get a chance to release it now - https://hackage.haskell.org/package/hoogle-5.0.17.11 now out

**Pull request merged**
