### PR TITLE
Added FromJSON instance for Target

### PR DESCRIPTION
**Pull request by meck**
I was working on a [client](https://github.com/meck/alfred-hoogle) for Hoogle as part of learning Haskell, and noticed that it would be good to have a ready Instance of fromJSON when I was using the Hoogle library for a json web client.

### CODE REVIEW

**Comment by ndmitchell** [comment]
Awesome patch!

**Comment by ndmitchell** [comment]
Let me know if you want a release to make your experimentation easier

**Comment by ndmitchell** [comment]
Btw, adding a test would be lovely, if you have the time/inclination. Just for one or two examples FromJSON/ToJSON is an identity.

**Comment by meck** [comment]
I just this minute discovered this was bad implementation, so you might want to revert it while I fix it and some tests. The optional records are encoded as ```{}``` if they are ```Nothing``` I thought they were omitted. Sorry

**Comment by ndmitchell** [comment]
Hehe, I'm not planning a release until you fix it, and it shouldn't break anything that doesn't use it, so will leave it for you to fix and test :)

**Pull request merged**
